/*
 * MoviesAndSeries.Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing SeriesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SeriesApiTests : IDisposable
    {
        private SeriesApi instance;

        public SeriesApiTests()
        {
            instance = new SeriesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SeriesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SeriesApi
            //Assert.IsType<SeriesApi>(instance);
        }

        /// <summary>
        /// Test ApiSeriesGet
        /// </summary>
        [Fact]
        public void ApiSeriesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ApiSeriesGet();
        }

        /// <summary>
        /// Test ApiSeriesListStartAmountGet
        /// </summary>
        [Fact]
        public void ApiSeriesListStartAmountGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int start = null;
            //int amount = null;
            //var response = instance.ApiSeriesListStartAmountGet(start, amount);
            //Assert.IsType<List<Series>>(response);
        }

        /// <summary>
        /// Test ApiSeriesNameQuantityPost
        /// </summary>
        [Fact]
        public void ApiSeriesNameQuantityPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //int quantity = null;
            //instance.ApiSeriesNameQuantityPost(name, quantity);
        }

        /// <summary>
        /// Test ApiSeriesPost
        /// </summary>
        [Fact]
        public void ApiSeriesPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ApiSeriesPost();
        }
    }
}
