/*
 * MoviesAndSeries.Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Series
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SeriesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Series
        //private Series instance;

        public SeriesTests()
        {
            // TODO uncomment below to create an instance of Series
            //instance = new Series();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Series
        /// </summary>
        [Fact]
        public void SeriesInstanceTest()
        {
            // TODO uncomment below to test "IsType" Series
            //Assert.IsType<Series>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'KinopoiskRating'
        /// </summary>
        [Fact]
        public void KinopoiskRatingTest()
        {
            // TODO unit test for the property 'KinopoiskRating'
        }
        /// <summary>
        /// Test the property 'ImdbRating'
        /// </summary>
        [Fact]
        public void ImdbRatingTest()
        {
            // TODO unit test for the property 'ImdbRating'
        }
        /// <summary>
        /// Test the property 'Episodes'
        /// </summary>
        [Fact]
        public void EpisodesTest()
        {
            // TODO unit test for the property 'Episodes'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Fact]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Fact]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }
        /// <summary>
        /// Test the property 'Poster'
        /// </summary>
        [Fact]
        public void PosterTest()
        {
            // TODO unit test for the property 'Poster'
        }

    }

}
